// Exports raylib's embedded default font (the pixel font every other platform
// draws) to a C header the iOS Metal renderer embeds, so iOS text matches the
// other platforms exactly. Needs a GL context (GetFontDefault uploads a
// texture), so run headless under xvfb:
//
//   gcc scripts/gen_font_atlas.c -Ithird_party/raylib-install/include \
//       -Lthird_party/raylib-install/lib -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 \
//       -o build/gen_font_atlas
//   xvfb-run -a ./build/gen_font_atlas > src/font_atlas.h
//
// Output: the atlas alpha bitmap + per-glyph metrics (rec, offset, advance) +
// baseSize, enough to reproduce raylib's DrawTextEx/MeasureTextEx exactly.
#include "raylib.h"
#include <stdio.h>

int main(void) {
    SetTraceLogLevel(LOG_ERROR);
    SetConfigFlags(FLAG_WINDOW_HIDDEN);
    InitWindow(64, 64, "gen_font_atlas");

    Font font = GetFontDefault();
    Image img = LoadImageFromTexture(font.texture);
    ImageFormat(&img, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8);
    const unsigned char* px = (const unsigned char*)img.data;
    int W = img.width, H = img.height;

    printf("// Generated by scripts/gen_font_atlas.c — raylib default pixel font.\n");
    printf("// Do not edit by hand; regenerate with the command in that file.\n");
    printf("#ifndef OPENRACKEM_FONT_ATLAS_H\n#define OPENRACKEM_FONT_ATLAS_H\n\n");
    printf("#define OB_FONT_ATLAS_W %d\n", W);
    printf("#define OB_FONT_ATLAS_H %d\n", H);
    printf("#define OB_FONT_BASE_SIZE %d\n", font.baseSize);
    printf("#define OB_FONT_GLYPH_COUNT %d\n\n", font.glyphCount);

    // Alpha coverage of the atlas (one byte per pixel).
    printf("static const unsigned char ob_font_atlas_alpha[OB_FONT_ATLAS_W * OB_FONT_ATLAS_H] = {\n");
    for (int i = 0; i < W * H; i++) {
        printf("%u,", px[i * 4 + 3]);
        if ((i % 32) == 31) printf("\n");
    }
    printf("};\n\n");

    printf("typedef struct { int value; float rx, ry, rw, rh; int ox, oy, adv; } OBGlyph;\n");
    printf("static const OBGlyph ob_font_glyphs[OB_FONT_GLYPH_COUNT] = {\n");
    for (int i = 0; i < font.glyphCount; i++) {
        Rectangle r = font.recs[i];
        GlyphInfo g = font.glyphs[i];
        printf("{%d,%g,%g,%g,%g,%d,%d,%d},\n",
               g.value, r.x, r.y, r.width, r.height, g.offsetX, g.offsetY, g.advanceX);
    }
    printf("};\n\n#endif // OPENRACKEM_FONT_ATLAS_H\n");

    UnloadImage(img);
    CloseWindow();
    return 0;
}
