#!/usr/bin/env python3
# Fetch the Mozilla CA bundle and emit it as a C byte array for the Android
# online client to compile in (net_posix.c, PLATFORM_ANDROID). Android has no
# CA store OpenSSL can find, so the roots must travel inside the binary. Kept out
# of git (third_party/cacert/ is gitignored) and regenerated at build time so the
# bundle stays fresh; pin/refresh via the URL below.
#
# Usage: gen_cacert.py <output-header-path>
import os
import sys
import urllib.request

URL = "https://curl.se/ca/cacert.pem"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "third_party/cacert/cacert_pem.h"
    data = urllib.request.urlopen(URL, timeout=60).read()  # noqa: S310 (fixed https URL)
    if b"BEGIN CERTIFICATE" not in data:
        sys.exit("gen_cacert: downloaded bundle has no certificates")
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write("// Generated by scripts/gen_cacert.py from %s — do not edit.\n" % URL)
        f.write("// Mozilla CA bundle embedded for Android (no OpenSSL-visible system store).\n")
        f.write("#ifndef OPENRACKEM_CACERT_PEM_H\n#define OPENRACKEM_CACERT_PEM_H\n")
        f.write("static const unsigned char cacert_pem[] = {\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned int cacert_pem_len = %du;\n" % len(data))
        f.write("#endif\n")
    print("gen_cacert: wrote %s (%d bytes)" % (out, len(data)))


if __name__ == "__main__":
    main()
